### ISSUE TITLE
Impossible to Customize Fixture Creation

### ISSUE THREAD

**Issue by sshymko** [doctrine/data-fixtures#122]
Currently, fixtures instantiation is hard-coded in `Doctrine\Common\DataFixtures\Loader` to use the [new operator](http://us3.php.net/manual/en/language.oop5.basic.php#language.oop5.basic.new). That prevents usage of widely-adopted practices of injecting dependencies on constructor.

Suggested solution: delegate fixtures creation to a factory and provide a machanism to pass the custom factory to the fixtures framework.

**Comment by augustohp** [comment]
This by itself does not resolve the problem, as [loading fixtures from a Diretory uses the `addFixture` method][1] that [allows only one instance per class to be used][2].

Using [SplObjectStorage][3] instead of an array with *class names* as key should solve the problem, but I don't know if it is a design choice to prevent that - using the same class over and over again - or not. If not, I am happy to implement those pieces.

[1]: https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/Loader.php#L103
[2]: https://github.com/doctrine/data-fixtures/blob/master/lib/Doctrine/Common/DataFixtures/Loader.php#L145
[3]: http://php.net/splobjectstorage

**Comment by lavoiesl** [comment]
This seems like too much refactor for little gain. If accepted, it wouldn’t be before 2.0. For dependency injection, look at [Symfony/DataFixtures/ContainerAwareLoader](https://github.com/symfony/DoctrineBridge/blob/master/DataFixtures/ContainerAwareLoader.php)

**Comment by lavoiesl** [comment]
Please reopen if you have ways to suggest to circumvent the refactor issue, especially because dependent fixtures are now instantiated on-the-fly: https://github.com/doctrine/data-fixtures/blob/59d52a6fc932c923382bd59a248b3cc147c20b16/lib/Doctrine/Common/DataFixtures/Loader.php#L138
