### ISSUE TITLE
doctrine/data-fixtures dev-master conflicts with doctrine/orm[2.2.3] > 2.4-dev

### ISSUE THREAD

**Issue by AITG** [doctrine/data-fixtures#189]
I've just gone to migrate a live box to a new release and it appears the release a couple of hours ago is broken.

Problem 1
    - doctrine/data-fixtures dev-master conflicts with doctrine/orm[2.2.3].
    - doctrine/data-fixtures dev-master conflicts with doctrine/orm[2.3.0].
    - doctrine/data-fixtures dev-master conflicts with doctrine/orm[2.3.1].
    - doctrine/data-fixtures dev-master conflicts with doctrine/orm[2.3.2].
    - doctrine/data-fixtures dev-master conflicts with doctrine/orm[2.3.3].
    - doctrine/data-fixtures dev-master conflicts with doctrine/orm[2.3.4].
    - doctrine/data-fixtures dev-master conflicts with doctrine/orm[2.3.5].
    - doctrine/data-fixtures dev-master conflicts with doctrine/orm[v2.3.6].
    - Installation request for doctrine/data-fixtures dev-master -> satisfiable by doctrine/data-fixtures[dev-master].
    - Installation request for doctrine/orm >=2.2.3,<2.4-dev -> satisfiable by doctrine/orm[2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, v2.3.6].

I ran this on a vm I setup yesterday (which setup fine yesterday) and it also failed to do a composer update, so it does appear that the release at 22:30 today UK time is severely broken.

**Comment by lavoiesl** [comment]
Now requires doctrine/orm >= 2.4 if you use doctrine/orm https://github.com/doctrine/data-fixtures/releases/tag/v1.1.0
This is because of #166. See #183

Solution: Update your composer.json to `"doctrine/orm": "~2.4"` or stay to `"doctrine/data-fixtures": "1.0.2"`. Heads up: 1.0.1 breaks compatibility but was not tagged as such, so do not use it.
